[versions]
compose-navigation = "2.5.0"
accompanist-permissions = "0.30.1"
camerax = "1.2.3"
mlkit-barcode = "17.2.0"

[libraries]
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist-permissions" }
camerax-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
camerax-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
camerax-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }
mlkit-barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "mlkit-barcode" }

[bundles]
barcode-scanning = ["camerax-camera2", "camerax-lifecycle", "camerax-view", "mlkit-barcode-scanning"]

[plugins]